site_name: The Project Docs
site_url: https://theprojectdocs.pages.dev/

repo_name: HiTECH-Corporation/The-Project-Docs
repo_url: https://github.com/HiTECH-Corporation/The-Project-Docs

theme:
  name: material
  
  logo: https://cdn.jsdelivr.net/gh/HiTECH-Corporation/The-Project-Docs@latest/assets/logo.svg
  favicon: https://cdn.jsdelivr.net/gh/HiTECH-Corporation/The-Project-Docs@latest/assets/favicon.png

  font:
    text: Inter
    code: JetBrains Mono
  
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - announce

  announcement:
    dismissible: true
    text: >
      **The Project Docs** is currently in beta. Report issues [here](https://github.com/HiTECH-Corporation/The-Project-Docs/issues).

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they\\'re searching for. With your consent, you\\'re helping us to
      make our documentation better.
        
plugins:
  - offline
  - monorepo
  - openapi # Thêm plugin openapi

extra:
  analytics: 
    provider: google
    property: G-XCKYETEH5E
    
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

nav:
  - Home: index.md
  - 1. Appearance: Appearance.md
  - zenOS:
      - Overview: zenOS/index.md
  - AuthKit API:
    - Welcome: AuthKit API/index.md
    - 'How to use (API v1)':
      - 'For Telegram': AuthKit API/h2u-avcapi-v1/for-telegram.md
      - 'For Email': AuthKit API/h2u-avcapi-v1/for-email.md
      - "Retrieve app's information": AuthKit API/h2u-avcapi-v1/retrieve-apps-information.md
    - Projects:
      - Python: AuthKit API/avcapi-project/python-project.md
      - Javascript: AuthKit API/avcapi-project/javascript-project.md
    - 'AppVerify Code API v2 (Coming soon)':
      - Changelog: AuthKit API/avcapi-v2/changelog.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed: {alternate_style: true}
  - pymdownx.highlight # Thêm extension này cho code blocks
  - pymdownx.snippets # Hữu ích cho việc nhúng các phần của file
  - def_list # Hữu ích cho các định nghĩa
  - footnotes # Hữu ích cho chú thích

